using System.Diagnostics;

namespace CommunityToolkit.Maui.Markup;

/// <summary>
/// <see cref="MauiAppBuilder"/> Extensions
/// </summary>
public static class AppBuilderExtensions
{
	/// <summary>
	/// Initializes the .NET MAUI Community Toolkit Markup Library
	/// </summary>
	/// <param name="builder"><see cref="MauiAppBuilder"/> generated by <see cref="MauiApp"/> </param>
	/// <returns><see cref="MauiAppBuilder"/> initialized for <see cref="CommunityToolkit.Maui.Markup"/></returns>
	public static MauiAppBuilder UseMauiCommunityToolkitMarkup(this MauiAppBuilder builder)
	{
		if (Debugger.IsAttached)
		{
			RegisterReloadApplicationEventHandler();
		}
		return builder;
	}
	
	static void RegisterReloadApplicationEventHandler()
	{
		CommunityToolkitMetadataUpdateHandler.ReloadApplication += ReloadApplication;
	}

	static void ReloadApplication(object? sender, IReadOnlyList<Type> e)
	{
		var hotReloadHandler = Application.Current?.Handler?.MauiContext?.Services.GetService<ICommunityToolkitHotReloadHandler>();
		hotReloadHandler?.OnHotReload(e);
	}
}