name: Benchmarks

on:
  push:
    branches:
      - main
    tags:
      - '*'
    paths-ignore:
      - README.md
  pull_request:
    branches:
      - '*'

env:
  LATEST_NET_VERSION: '10.0.x'
  PathToCommunityToolkitBenchmarkCsproj: 'src/CommunityToolkit.Maui.Markup.Benchmarks/CommunityToolkit.Maui.Markup.Benchmarks.csproj'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  run_benchmarks:
    name: Run Benchmarks
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-26]

    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - uses: maxim-lobanov/setup-xcode@ed7a3b1fda3918c0306d1b724322adc0b8cc0a90 # v1
        if: runner.os == 'macOS'
        with:
          xcode-version: latest-stable

      - name: Install Latest Version of .NET, v${{ env.LATEST_NET_VERSION }}
        uses: actions/setup-dotnet@26b0ec14cb23fa6904739307f278c14f94c95bf1 # v5
        with:
          dotnet-version: ${{ env.LATEST_NET_VERSION }}
          dotnet-quality: 'ga'

      - name: Install .NET MAUI Workload
        run: |
          dotnet workload install maui
          dotnet workload update

      - name: Install Tizen Workload
        run: |
          Invoke-WebRequest 'https://raw.githubusercontent.com/Samsung/Tizen.NET/main/workload/scripts/workload-install.ps1' -OutFile 'workload-install.ps1'
          .\workload-install.ps1
        shell: pwsh

      - name: Display dotnet info
        run: dotnet --info

      - name: Run Benchmarks
        run: dotnet run --project ${{ env.PathToCommunityToolkitBenchmarkCsproj }} -c Release -- -a ${{ runner.temp }}

      - name: Publish Benchmarks
        if: runner.os == 'Windows'
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        with:
          name: Benchmarks
          path: |
            ${{ runner.temp }}/**/*.md