name: CommunityToolkit.Maui.Markup

on:
  push:
    branches:
      - "main"
  pull_request:
    branches: 
      - "*"

jobs:
    Build_macOS:
      runs-on: macos-latest

      steps:
        - uses: actions/checkout@v1
          
        - name: Setup .NET v6.0
          uses: actions/setup-dotnet@v1
          with:
            dotnet-version: '6.0.x'
            include-prerelease: true

        - name: Install .NET MAUI Workload
          run: |
            dotnet workload install maui
          
        - name: Restore NuGet 
          run: |
            dotnet restore ./src/

        - name: Build
          run: |
            dotnet build ./src/

    UnitTest_macOS:
      runs-on: macos-latest
      needs: Build_macOS

      steps:
      - uses: actions/checkout@v1
        
      - name: Setup .NET v6.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
          include-prerelease: true

      - name: Install .NET MAUI Workload
        run: |
          dotnet workload install maui
        
      - name: Restore NuGet 
        run: |
          dotnet restore ./src/
          
      - name: Run Unit Tests
        run: |   
          UnitTestProject=`find . -name CommunityToolkit.Maui.Markup.UnitTests.csproj`
          echo $UnitTestProject
          
          dotnet test  -c Release $UnitTestProject

    Build_Windows:
      runs-on: windows-latest

      steps:
        - uses: actions/checkout@v1
          
        - name: Setup .NET v6.0
          uses: actions/setup-dotnet@v1
          with:
            dotnet-version: '6.0.x'
            include-prerelease: true

        - name: Install .NET MAUI Workload
          run: |
            dotnet workload install maui
          
        - name: Restore NuGet 
          run: |
            dotnet restore ./src/

        - name: Build 
          run: |
            dotnet build ./src/

    UnitTest_Windows:
      runs-on: macos-latest
      needs: Build_Windows

      steps:
      - uses: actions/checkout@v1
        
      - name: Setup .NET v6.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
          include-prerelease: true

      - name: Install .NET MAUI Workload
        run: |
          dotnet workload install maui
        
      - name: Restore NuGet 
        run: |
          dotnet restore ./src/
          
      - name: Run Unit Tests
        run: |   
          UnitTestProject=`find . -name CommunityToolkit.Maui.Markup.UnitTests.csproj`
          echo $UnitTestProject
          
          dotnet test  -c Release $UnitTestProject
