name: Samples

on:
  push:
    branches:
      - "main"
  pull_request:
    branches: 
      - "*"

jobs:
    Build_Sample_macOS:
      runs-on: macos-latest

      steps:
        - uses: actions/checkout@v1
          
        - name: Setup .NET v6.0
          uses: actions/setup-dotnet@v1
          with:
            dotnet-version: '6.0.x'
            include-prerelease: true

        - name: Install .NET MAUI Workload
          run: |
            dotnet workload install maui
          
        - name: Restore NuGet 
          run: |
            dotnet restore ./samples/

        - name: Build
          run: |
            dotnet build ./samples/ -c Release

    Build_Sample_Windows:
      runs-on: windows-latest

      steps:
        - uses: actions/checkout@v1
          
        - name: Setup .NET v6.0
          uses: actions/setup-dotnet@v1
          with:
            dotnet-version: '6.0.x'
            include-prerelease: true

        - name: Install .NET MAUI Workload
          run: |
            dotnet workload install maui
          
        - name: Restore NuGet 
          run: |
            dotnet restore ./samples/

        - name: Build 
          run: |
            dotnet build ./samples/ -c Release
